#version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: python-backend
    ports:
      - "8000:8000"
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_started
    env_file:
      - ./backend/.env
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: myminioadmin
      MINIO_ROOT_PASSWORD: mystrongpassword
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data
    networks:
      - mynetwork
volumes:
  mysql_data:
  minio_data:
networks:
  mynetwork: